# Generated by Django 4.2.4 on 2024-01-18 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_info_img_alter_info_text_alter_info_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='img',
        ),
    ]
