# Generated by Django 4.2.4 on 2024-01-19 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_about_remove_info_text_remove_info_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.CharField(blank=True, max_length=55, null=True, validators=[django.core.validators.RegexValidator(code='Invalid email', message='Invalide email', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.CharField(blank=True, max_length=55, null=True, validators=[django.core.validators.RegexValidator(code='Invalid email', message='Invalide email', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(code='Invalid number', message='Invalide phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')]),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.CharField(blank=True, max_length=55, null=True, validators=[django.core.validators.RegexValidator(code='Invalid email', message='Invalide email', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AddField(
            model_name='contact',
            name='yutube',
            field=models.CharField(blank=True, max_length=55, null=True, validators=[django.core.validators.RegexValidator(code='Invalid email', message='Invalide email', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='Invalid email', message='Invalide email', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='Invalid email', message='Invalide email', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
    ]
